const items = [
  {
    id: '1',
    name: 'YELLOW CHIMES Charming',
    image:'/assets/images/earring1.png',
    image_alt: 'earring1',
    original_price: 10999,
    current_price: 9999,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '2',
    name: 'Rubans Gold Plated',
    image:'/assets/images/earring2.png',
    image_alt: 'earring2',
    original_price: 10800,
    current_price: 7999,
    delivery_date:'18-10-2025',
    wishlist:false,
  },
  {
    id: '3',
    name: 'LUXOR Temple',
    image:'/assets/images/earring3.png',
    image_alt: 'earring3',
    original_price: 1090,
    current_price: 7909,
    delivery_date:'18-10-2026',
    wishlist:false,
  },
  {
    id: '4',
    name: 'Chocozone',
    image:'/assets/images/earring4.png',
    image_alt: 'earring4',
    original_price: 12000,
    current_price: 7099,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '5',
    name: 'Karishma Kreations',
    image:'/assets/images/earring5.png',
    image_alt: 'earring5',
    original_price: 10099,
    current_price: 9099,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '6',
    name: 'TREADEX Trendy Alloy',
    image:'/assets/images/ring1.webp',
    image_alt: 'ring1',
    original_price: 8800,
    current_price: 6699,
    delivery_date:'18-10-2024',
    wishlist:false,
  }, 
  {
    id: '7',
    name: 'MYKI Solitaire',
    image:'/assets/images/ring3.png',
    image_alt: 'ring2',
    original_price: 10000,
    current_price: 7999,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '8',
    name: 'GIVA Sterling Silver',
    image:'/assets/images/ring4.png',
    image_alt: 'ring3',
    original_price: 9000,
    current_price: 7999,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '9',
    name: 'YELLOW CHIMES Crystal',
    image:'/assets/images/ring5.png',
    image_alt: 'ring4',
    original_price: 12000,
    current_price: 9995,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '10',
    name: 'Golden Crystal Blue',
    image:'/assets/images/ring6.png',
    image_alt: 'ring5',
    original_price: 11999,
    current_price: 8999,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '11',
    name: 'BOGHRA SALES Chain',
    image:'/assets/images/locket1.png',
    image_alt: 'neckwear1',
    original_price: 8800,
    current_price: 6699,
    delivery_date:'18-10-2024',
    wishlist:false,
  },
  {
    id: '12',
    name: 'Atasi Alloy',
    image:'/assets/images/locket2.png',
    image_alt: 'neckwear2',
    original_price: 9800,
    current_price: 8699,
    delivery_date:'18-11-2025',
    wishlist:false,
  },
  {
    id: '13',
    name: 'Ambal Dori Jewellery',
    image:'/assets/images/locket3.png',
    image_alt: 'neckwear3',
    original_price: 9800,
    current_price: 6699,
    delivery_date:'08-10-202',
    wishlist:false,
  },
  {
    id: '14',
    name: 'Brado Jewellery',
    image:'/assets/images/locket4.png',
    image_alt: 'neckwear4',
    original_price: 14800,
    current_price: 8899,
    delivery_date:'14-01-2025',
    wishlist:false,
  },
  {
    id: '15',
    name: 'LJJEWELLER Gold-plated',
    image:'/assets/images/locket5.png',
    image_alt: 'neckwear5',
    original_price: 12800,
    current_price: 9699,
    delivery_date:'18-10-2025',
    wishlist:false,
  },
] 